serviceType: Deployment
displayName: test
dockerfileName: Dockerfile
dockerContext: .
k8sSettings:
  limitCpuCores: 0.3
  limitMemoryMB: 100
  ephemeralStorageMB: 50
  replicaCount: 1
  deploymentStrategy: recreate
  imagePullPolicy: Always
  probesOn: false
envVars: []
ports:
  - portType: HTTPS
    internalPort: 8080
    externalPort: 80
    expose: true

