serviceType: Deployment
displayName: Frontedntest
dockerfileName: Dockerfile
dockerContext: .
k8sSettings:
  limitCpuCores: 0.6
  limitMemoryMB: 30
  ephemeralStorageMB: 50
  replicaCount: 1
  deploymentStrategy: recreate
  imagePullPolicy: IfNotPresent
envVars:
  - id: fd332daf-f8e5-4b75-b755-fa252eef484e
    name: MYSQL_PASSWORD
    data:
      type: KEY_VAULT
      vaultType: MOGENIUS_VAULT
    type: KEY_VAULT
ports: []

