serviceType: Deployment
displayName: webapp4711
dockerfileName: Dockerfile
dockerContext: .
k8sSettings:
  limitCpuCores: 0.5
  limitMemoryMB: 100
  ephemeralStorageMB: 50
  replicaCount: 1
  deploymentStrategy: recreate
  imagePullPolicy: IfNotPresent
  probesOn: false
envVars: []
ports:
  - portType: HTTPS
    internalPort: 8080
    externalPort: 80
    expose: true

