serviceType: Deployment
displayName: webapp
dockerfileName: Dockerfile
dockerContext: .
k8sSettings:
  limitCpuCores: 1.1
  limitMemoryMB: 50
  ephemeralStorageMB: 50
  replicaCount: 1
  deploymentStrategy: recreate
  imagePullPolicy: IfNotPresent
  probesOn: false
envVars: []
ports:
  - portType: HTTPS
    internalPort: 8080
    externalPort: 80
    expose: false

