serviceType: GIT_REPOSITORY
displayName: AngularDemo
gitRepository: https://github.com/janlepsky/AngularDemo.git
gitBranch: Dev
dockerfileName: Dockerfile
dockerContext: .
k8sSettings:
  limitCpuCores: 0.2
  limitMemoryMB: 60
  ephemeralStorageMB: 50
  replicaCount: 4
  deploymentStrategy: rolling
  imagePullPolicy: IfNotPresent
  probesOn: false
envVars: []
ports:
  - portType: HTTPS
    internalPort: 8080
    externalPort: 80
    expose: true
app: null

