serviceType: Deployment
displayName: Repo
dockerfileName: Dockerfile
dockerContext: .
k8sSettings:
  limitCpuCores: 0.3
  limitMemoryMB: 50
  ephemeralStorageMB: 50
  replicaCount: 1
  deploymentStrategy: recreate
  imagePullPolicy: IfNotPresent
envVars: []
ports: []

